import React from 'react'
import CARD from '../card/CARD'
import rose from '../card/rose.jpeg'
export default function CARDS_CONTAINER(props) {
    
    return (
        <>
            <div className='cards-container'>
            <CARD 
                image={rose}
                counter={props.counter}
                setcounter={props.setcounter}
                />
                  <CARD 
                image={rose}
                counter={props.counter}
                setcounter={props.setcounter}
                />
                  <CARD 
                image={rose}
                counter={props.counter}
                setcounter={props.setcounter}
                />
                  <CARD 
                image={rose}
                counter={props.counter}
                setcounter={props.setcounter}
                />
                  <CARD 
                image={rose}
                counter={props.counter}
                setcounter={props.setcounter}
                />
                  <CARD 
                image={rose}
                counter={props.counter}
                setcounter={props.setcounter}
                />
                  <CARD 
                image={rose}
                counter={props.counter}
                setcounter={props.setcounter}
                />
                  <CARD 
                image={rose}
                counter={props.counter}
                setcounter={props.setcounter}
                />
                  <CARD 
                image={rose}
                counter={props.counter}
                setcounter={props.setcounter}
                />
                  <CARD 
                image={rose}
                counter={props.counter}
                setcounter={props.setcounter}
                />
                        <CARD 
                image={rose}
                counter={props.counter}
                setcounter={props.setcounter}
                />
                        <CARD 
                image={rose}
                counter={props.counter}
                setcounter={props.setcounter}
                />
                        <CARD 
                image={rose}
                counter={props.counter}
                setcounter={props.setcounter}
                />
                        <CARD 
                image={rose}
                counter={props.counter}
                setcounter={props.setcounter}
                />
            </div>
        </>
    )
}
